// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCb8ivJtc_bFTt9xvonMVCCEvNqBh5MZW8',
    appId: '1:840344127632:web:14e2c5b91ec1aef2617015',
    messagingSenderId: '840344127632',
    projectId: 'todo-flut',
    authDomain: 'todo-flut.firebaseapp.com',
    storageBucket: 'todo-flut.appspot.com',
    measurementId: 'G-ZQQYBS5RDD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXrsnk27ppxrEu1yqn9NmTShhAw9pWa14',
    appId: '1:840344127632:android:88f262d9e92c311c617015',
    messagingSenderId: '840344127632',
    projectId: 'todo-flut',
    storageBucket: 'todo-flut.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAjVIqIMGWMn0Fk5nsXDtpUVvD2Du815I',
    appId: '1:840344127632:ios:4c012a4f345c9545617015',
    messagingSenderId: '840344127632',
    projectId: 'todo-flut',
    storageBucket: 'todo-flut.appspot.com',
    iosBundleId: 'com.example.todoProjectJeongdeokho',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDAjVIqIMGWMn0Fk5nsXDtpUVvD2Du815I',
    appId: '1:840344127632:ios:4c012a4f345c9545617015',
    messagingSenderId: '840344127632',
    projectId: 'todo-flut',
    storageBucket: 'todo-flut.appspot.com',
    iosBundleId: 'com.example.todoProjectJeongdeokho',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCb8ivJtc_bFTt9xvonMVCCEvNqBh5MZW8',
    appId: '1:840344127632:web:9beb898b92faa85d617015',
    messagingSenderId: '840344127632',
    projectId: 'todo-flut',
    authDomain: 'todo-flut.firebaseapp.com',
    storageBucket: 'todo-flut.appspot.com',
    measurementId: 'G-9P2QKEC5WB',
  );

}